import mongoose from "mongoose";
import { AuditTrailSchema } from "./common/AuditTrail";

/**
 * Schema for Individual Information Visibility Settings.
 *
 * @typedef {Object} individual_info_visibilitySchema
 * @property {mongoose.Schema.Types.ObjectId} IIV_Visibility_Id - Unique identifier for the individual visibility settings (Auto-generated by MongoDB).
 * @property {mongoose.Schema.Types.ObjectId} IIV_Individual_Id - Reference to the individual's profile (Required).
 * @property {Boolean} IIV_Phone_Number - Set privacy for the user's contact number visibility (Switch: true/false).
 * @property {Boolean} IIV_Email - Set privacy for the user's email visibility (Switch: true/false).
 * @property {Boolean} IIV_BirthDate - Set privacy for the user's birthdate visibility (Switch: true/false).
 * @property {Boolean} IIV_Address_Line1 - Set privacy for the user's address line 1 visibility (Switch: true/false).
 * @property {Boolean} IIV_Address_Line2 - Set privacy for the user's address line 2 visibility (Switch: true/false).
 * @property {Boolean} IIV_Landmark - Set privacy for the user's landmark visibility (Switch: true/false).
 * @property {Boolean} IIV_Pincode - Set privacy for the user's pincode visibility (Switch: true/false).
 * @property {Boolean} IIV_Website_Url_Visibility - Set privacy for the user's website URL visibility (Switch: true/false).
 * @property {Number} IIV_Session_Id - Session identifier where the record was created (Optional).
 * @property {Date} IIV_Creation_DtTym - Date and time when the visibility record was created (Default: Current timestamp).
 * @property {Array.<AuditTrailSchema>} IIV_Audit_Trail - Audit trail information for tracking changes (Optional).
 * @property {Date} createdAt - The timestamp when the document was created (Managed by Mongoose).
 * @property {Date} updatedAt - The timestamp when the document was last updated (Managed by Mongoose).
 */


const individual_info_visibilitySchema = new mongoose.Schema(
  {
    IIV_Individual_Id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "individual_details", // Reference to individual
      required: true,
    },
    IIV_Phone_Number: { type: Boolean, default: false }, 
    IIV_Email: { type: Boolean, default: false },
    IIV_BirthDate: { type: Boolean, default: false },
    IIV_Address_Line1: { type: Boolean, default: false },
    IIV_Address_Line2: { type: Boolean, default: false },
    IIV_Landmark: { type: Boolean, default: false },
    IIV_Pincode: { type: Boolean, default: false },
    IIV_Website_Url_Visibility: { type: Boolean, default: false },
    IIV_Session_Id: { type: Number },
    IIV_Creation_DtTym: { type: Date, default: Date.now },
    IIV_Audit_Trail: [AuditTrailSchema],
  },
  {
    timestamps: true, // Mongoose will handle createdAt and updatedAt
  }
);

export default mongoose.models.individual_info_visibility ||
  mongoose.model(
    "individual_info_visibility",
    individual_info_visibilitySchema
  );
